# Baseline Model

Always predicts the most common class (neutral)

In [1]:
!pip install pyprojroot

Collecting pyprojroot
  Downloading pyprojroot-0.3.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pyprojroot) (4.15.0)
Downloading pyprojroot-0.3.0-py3-none-any.whl (7.6 kB)
Installing collected packages: pyprojroot
Successfully installed pyprojroot-0.3.0

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import polars as pl

from pyprojroot import here

In [4]:
# Load train and test data
train = pl.scan_parquet("drive/MyDrive/Data/train_reduced.parquet")
test = pl.scan_parquet("drive/MyDrive/Data/test_reduced.parquet")

In [5]:
def fill_neutral_predictions(dataset: pl.DataFrame) -> pl.DataFrame:
  return dataset.with_columns(
      pl.lit(0).alias("conservative"),
      pl.lit(1).alias("neutral"),
      pl.lit(0).alias("liberal"),
      pl.lit("neutral").alias("prediction"),
  )

In [6]:
train = fill_neutral_predictions(train)
test = fill_neutral_predictions(test)

In [7]:
train.head(10).collect()

shape: (10, 11)
┌──────────┬─────────┬─────────────┬─────────────┬───┬────────────┬─────────┬─────────┬────────────┐
│ index    ┆ id      ┆ subreddit   ┆ username    ┆ … ┆ conservati ┆ neutral ┆ liberal ┆ prediction │
│ ---      ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ve         ┆ ---     ┆ ---     ┆ ---        │
│ u32      ┆ str     ┆ str         ┆ str         ┆   ┆ ---        ┆ i32     ┆ i32     ┆ str        │
│          ┆         ┆             ┆             ┆   ┆ i32        ┆         ┆         ┆            │
╞══════════╪═════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪═════════╪════════════╡
│ 3952889  ┆ cwh8hsc ┆ movies      ┆ Reagan__pre ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ sley        ┆   ┆            ┆         ┆         ┆            │
│ 5620964  ┆ daguwpp ┆ movies      ┆ Lou-Read    ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 20484533 ┆ ch0ymih ┆ Cooking     ┆ artard      ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 30428388 ┆ dvk1tyi ┆ CasualConve ┆ TrumpCardWa ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ rsation     ┆ sTaken      ┆   ┆            ┆         ┆         ┆            │
│ 2705286  ┆ cly4x7d ┆ movies      ┆ DarthBatman ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ 666         ┆   ┆            ┆         ┆         ┆            │
│ 15156380 ┆ csx4s3r ┆ explainlike ┆ amz1018     ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ imfive      ┆             ┆   ┆            ┆         ┆         ┆            │
│ 33414535 ┆ djsnytq ┆ AskMen      ┆ ImpeachTrum ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ pASAP       ┆   ┆            ┆         ┆         ┆            │
│ 3953787  ┆ cwhfbqc ┆ movies      ┆ Reagan__pre ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ sley        ┆   ┆            ┆         ┆         ┆            │
│ 29260988 ┆ crrmrmp ┆ CasualConve ┆ FloFromProg ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ rsation     ┆ ressive     ┆   ┆            ┆         ┆         ┆            │
│ 27390716 ┆ cvoojqm ┆ camping     ┆ videomiliti ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ a           ┆   ┆            ┆         ┆         ┆            │
└──────────┴─────────┴─────────────┴─────────────┴───┴────────────┴─────────┴─────────┴────────────┘

In [8]:
test.head(10).collect()

shape: (10, 11)
┌──────────┬─────────┬─────────────┬─────────────┬───┬────────────┬─────────┬─────────┬────────────┐
│ index    ┆ id      ┆ subreddit   ┆ username    ┆ … ┆ conservati ┆ neutral ┆ liberal ┆ prediction │
│ ---      ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ve         ┆ ---     ┆ ---     ┆ ---        │
│ u32      ┆ str     ┆ str         ┆ str         ┆   ┆ ---        ┆ i32     ┆ i32     ┆ str        │
│          ┆         ┆             ┆             ┆   ┆ i32        ┆         ┆         ┆            │
╞══════════╪═════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪═════════╪════════════╡
│ 11508213 ┆ d0oshg2 ┆ Fitness     ┆ Magahaka    ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 8398748  ┆ caphney ┆ gardening   ┆ louchar     ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 28204105 ┆ cwufxng ┆ Fantasy     ┆ xolsiion    ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 7887909  ┆ e22e4z8 ┆ movies      ┆ LivnLegndNe ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ edsEggs     ┆   ┆            ┆         ┆         ┆            │
│ 2411655  ┆ cjblu8y ┆ movies      ┆ RandomJPG6  ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│ 29022391 ┆ co9jeo6 ┆ CasualConve ┆ Wooble_Gop  ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ rsation     ┆             ┆   ┆            ┆         ┆         ┆            │
│ 35839305 ┆ caarcbr ┆ photography ┆ HoshPoshMos ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆             ┆ h           ┆   ┆            ┆         ┆         ┆            │
│ 12855341 ┆ cht8ktz ┆ MechanicAdv ┆ IhateFoxnew ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ ice         ┆ s           ┆   ┆            ┆         ┆         ┆            │
│ 16283734 ┆ deuctoh ┆ explainlike ┆ harley4570  ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
│          ┆         ┆ imfive      ┆             ┆   ┆            ┆         ┆         ┆            │
│ 28287224 ┆ d5vofza ┆ Fantasy     ┆ fiercefalco ┆ … ┆ 0          ┆ 1       ┆ 0       ┆ neutral    │
└──────────┴─────────┴─────────────┴─────────────┴───┴────────────┴─────────┴─────────┴────────────┘

In [10]:
train.sink_parquet("drive/MyDrive/Data/train_reduced_baseline.parquet")
test.sink_parquet("drive/MyDrive/Data/test_reduced_baseline.parquet")